SELECT  MRN,
		PATIENTID,
		DOB,
		SEX,
		ZIPCODE,
		CENSUSBLOCK,
        CENSUSTRACT,
        CENSUSBLOCKGROUP,
        CENSUSBLOCKGROUPID,
		ll.PREFERREDLANGUAGEDESC AS LANGUAGE,--PREFERREDLANGUAGEID,
		lm.MARITALSTATUSDESC,--MARITALSTATUSID,
		lem.EMPLOYMENTSTATUSDESC,--EMPLOYMENTSTATUSID,
		lrel.RELIGIONDESC,--RELIGIONID,
		lo.OCCUPATIONDESC,--OCCUPATIONID,
		lc.COUNTRYDESC,--COUNTRY_OF_ORIGIN_ID,
		le.ETHNICITYDESC,
		lr.RACEDESC,
		GRANULAR_ETHNICITY_ID,
		GRANULAR_RACE_ID
FROM EDM.PATIENTS@EDWPROD pat
LEFT JOIN EDM.LOOKUPPREFERREDLANGUAGE ll ON pat.PREFERREDLANGUAGEID = ll.PREFERREDLANGUAGEID
LEFT JOIN EDM.LOOKUPMARITALSTATUS lm ON pat.MARITALSTATUSID = lm.MARITALSTATUSID
LEFT JOIN EDM.LOOKUPEMPLOYMENTSTATUS lem ON pat.EMPLOYMENTSTATUSID = lem.EMPLOYMENTSTATUSID
LEFT JOIN EDM.LOOKUPRELIGION lrel ON pat.RELIGIONID = lrel.RELIGIONID
LEFT JOIN EDM.LOOKUPOCCUPATION lo ON pat.OCCUPATIONID = lo.OCCUPATIONID
LEFT JOIN EDM.LOOKUPCOUNTRY lc ON pat.COUNTRY_OF_ORIGIN_ID = lc.COUNTRYID
LEFT JOIN EDM.LOOKUPETHNICITY le ON pat.ETHNICITYID = le.ETHNICITYID
LEFT JOIN EDM.LOOKUPRACE lr ON pat.RACEID = lr.RACEID
-- WHERE pat.MRN IN ('05938034','02705513','02705513','06189430','05840688')
WHERE pat.MRN IN ({mrn_list})